Pass positional argument 'context' to BasicClobberError
Issue can be reproduced by:

(root) $ touch /tmp/src.tar.gz
(root) $ python3 -c '
from conda import fetch;
fetch.download(url="file:///tmp/src.tar.gz", dst_path="dest.tar.gz")'
(root) $ python3 -c '
from conda import fetch;
fetch.download(url="file:///tmp/src.tar.gz", dst_path="dest.tar.gz")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/condadev3/lib/python3.5/site-packages/conda/core/package_cache.py", line 514, in download
    gateway_download(url, dst_path, md5)
  File "/tmp/condadev3/lib/python3.5/site-packages/conda/gateways/download.py", line 55, in download
    maybe_raise(BasicClobberError(target_full_path, url, context))
TypeError: maybe_raise() missing 1 required positional argument: 'context'

BasicClobberError(): 'context' is a _required_ argument